-- ANALYZE THE MONTH OVER MONTH PERFORMANCE BY FINDING CHANGE IN SALES PERCENTAGE

SELECT *, ROUND(CAST(( Curr_Month_Sales-Prev_Month_Sales ) AS FLOAT )/ Prev_Month_Sales * 100,2) MoM_Perc FROM
(SELECT
	MONTH(OrderDate) Months,
	SUM(Sales) Curr_Month_Sales,
	LAG(SUM(Sales)) OVER(ORDER BY MONTH(OrderDate)) Prev_Month_Sales
FROM Sales.Orders
GROUP BY MONTH(OrderDate)
)t;

--IN ORDER TO ANALYZE CUSTOMER LOYALITY RANK CUSTOMER BASED ON AVERAGE DAYS BETWEEN THIER ORDERS

SELECT 
	CustomerID,
	AVG(DaysUntilNextOrder) AverageOrderDays,
	RANK() OVER(ORDER BY COALESCE(AVG(DaysUntilNextOrder),99999)) Ranking
FROM
	(SELECT
		CustomerID, OrderDate CurrentOrderDate,
		LEAD(OrderDate) OVER(PARTITION BY CustomerID ORDER BY OrderDate) NextOrderDate,
		DATEDIFF(DAY,OrderDate,LEAD(OrderDate) OVER(PARTITION BY CustomerID ORDER BY OrderDate)) DaysUntilNextOrder
	FROM Sales.Orders
)t
GROUP BY CustomerID;


--FIND THE LOWEST and HIGHEST SALES OF EACH PRODUCT
--FIND THE DIFFERENCE BETWEEN CURRENT MONTH SALES AND LOWEST SALES

SELECT 
	ProductID, Sales,
	FIRST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales) LowestSale,
	LAST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) HighestSale1,
	LAST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) HighestSale2,
	FIRST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales DESC) HighestSale3
FROM Sales.Orders;

SELECT 
	ProductID, Sales,
	FIRST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales) LowestSale,
	Sales - FIRST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales) DiffSale
FROM Sales.Orders;